In [3]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("sales_train_v2.csv")

In [28]:
d=df[:10000]

In [29]:
d=d.dropna()

In [36]:
X = d.drop(labels = ["date","item_cnt_day"],axis=1)

In [37]:
X

date_block_num  shop_id  item_id  item_price
0                  0       59    22154      999.00
1                  0       25     2552      899.00
2                  0       25     2552      899.00
3                  0       25     2554     1709.05
4                  0       25     2555     1099.00
5                  0       25     2564      349.00
6                  0       25     2565      549.00
7                  0       25     2572      239.00
8                  0       25     2572      299.00
9                  0       25     2573      299.00
10                 0       25     2574      399.00
11                 0       25     2574      399.00
12                 0       25     2574      399.00
13                 0       25     2574      399.00
14                 0       25     2574      399.00
15                 0       25     2574      399.00
16                 0       25     2574      399.00
17                 0       25     2574      399.00
18                 0       25     2574      399.00
19                 0       25     2574      399.00
20                 0       25     2593      279.00
21                 0       25     2604      299.00
22                 0       25     2604      299.00
23                 0       25     2607      279.00
24                 0       25     2607      279.00
25                 0       25     2609     1699.00
26                 0       25     2548     1708.95
27                 0       25     2611      299.00
28                 0       25     2546      299.00
29                 0       25     2515     1649.00
...              ...      ...      ...         ...
9970               0       19     1790     1799.00
9971               0       19     1791     1799.00
9972               0       19     1800      274.00
9973               0       19     1800      274.50
9974               0       19     1800      549.00
9975               0       19     1800      274.00
9976               0       19     1830      599.00
9977               0       19     1830      599.00
9978               0       19     1830      599.00
9979               0       19     1830      599.00
9980               0       19     1624      299.00
9981               0       19     1023      299.00
9982               0       19     1021      399.00
9983               0       19     1021      399.00
9984               0       18    22091      109.00
9985               0       18    22092      109.00
9986               0       18    22092      109.00
9987               0       18    22092      109.00
9988               0       18    22092      109.00
9989               0       18    22092      109.00
9990               0       18    22092      109.00
9991               0       18    22061       58.00
9992               0       18    22134      399.00
9993               0       18    22134      399.00
9994               0       18    22135      549.00
9995               0       18    22139      791.12
9996               0       18    22140      499.00
9997               0       18    22140      349.50
9998               0       18    22151      399.00
9999               0       19       27     2499.00

[10000 rows x 4 columns]

In [38]:
Y = d["item_cnt_day"].values

In [39]:
Y

array([ 1.,  1., -1., ...,  1.,  1.,  1.])

In [40]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=12)

In [41]:
#averaging
voting = VotingClassifier(estimators=[
    ('Logreg', LogisticRegression()),
    ('KNC', KNeighborsClassifier()),
    ('DTC', DecisionTreeClassifier())
], voting='soft')

In [42]:
voting.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


VotingClassifier(estimators=[('Logreg',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('KNC',
                              KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski...
                                            

In [43]:
predictions = voting.predict(x_test)

In [44]:
predictions

array([1., 1., 1., ..., 1., 1., 1.])

In [46]:
voting.score(x_test, y_test)

0.8805

In [48]:
#voting
voting1 = VotingClassifier(estimators=[
    ('Logreg', LogisticRegression()),
    ('KNC', KNeighborsClassifier()),
    ('DTC', DecisionTreeClassifier())
])

In [49]:
voting1.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


VotingClassifier(estimators=[('Logreg',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('KNC',
                              KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski...
                                            

In [53]:
predictions1 = voting1.predict(x_test)

In [54]:
predictions1

array([1., 1., 1., ..., 1., 1., 1.])

In [55]:
confusion_matrix(y_test, predictions1)

array([[   0,    7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0, 1753,   12,    3,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,  144,    4,    2,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,   38,    3,    2,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,   15,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    3,    1,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    5,    1,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    1,    0,    0,    0,    0,    0, 

In [56]:
voting1.score(x_test, y_test)

0.8795